#!/usr/bin/env bash
# prints "Best School" 10 times, with "bad luck" as 4th iteration and "good luck" as 8th iteration

counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
	echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
